### ISSUE TITLE
How do you use the designs to create (uniform) random numbers on the desired interval?

### ISSUE THREAD

**Issue by deKeijzer** [toledo60/pyLHD#1]
Hi there, 

Nice package you got there! 

Could you provide an example of how to use a design to produce random numbers from the desired distribution? 

Say that I would like a 2D random Latin hypercube with $x \in [-2, 0.5)$ and $y \in [-2, 2)$. 

Is it possible to create that with pyLHD?

**Comment by toledo60** [comment]
@deKeijzer Thanks! currently this feature is not implemented in the package, but eventually it will be added. I've added links to a python package and discussion to the feature you are looking for

https://smt.readthedocs.io/en/latest/_src_docs/sampling_methods/lhs.html

https://stackoverflow.com/questions/66977657/latin-hypercube-sampling

Hope this helps!

**Comment by deKeijzer** [comment]
@toledo60 Ah that is unfortunate. Thank you for the fast reply and additional sources! I'll definitely use them.
